### PR TITLE
Code formatting changes for readability

### PR DESCRIPTION
**Pull request by alexpersian**
## Description
* Splits dictionaries into more digestible blocks and aligns them in a more readable way.
* Fixes some formatting issues with the documentation.

## Motivation and Context
This PR simply aims to make the code more readable.

## How Has This Been Tested?
No logic changes were made. Existing tests were run and passed.

### CODE REVIEW

**Comment by billabt** [comment]
Did you submit a CLA?  Can't take any contributions without it. Thanks.

**Comment by alexpersian** [comment]
@billabt I have filled out and signed the CLA, but was unable to find the correct email address to send it to. The only address listed was a mailing address for @kweinmeister, who I reached out to on Twitter for an email but haven't heard back.

**Comment by alexpersian** [comment]
@billabt was delayed this weekend, but just sent out the signed CLA this morning.

**Comment by billabt** [comment]
You have the right email now?

**Comment by kweinmeister** [comment]
The CLA was received. Thanks @alexpersian!

**Pull request merged**
