### PR TITLE
Migrated to swift 3 for OSX

### PR DESCRIPTION
**Pull request by hang-h**
Migrated to swift 3 for OSX

### CODE REVIEW

**Comment by billabt** [comment]
Thanks for the contribution. What version off the toolchain are you using?

**Comment by kweinmeister** [comment]
Also, have you filled out a [CLA](https://github.com/IBM-Swift/CLA) to consider your PR?

**Comment by kweinmeister** [comment]
@hang-h Hi Hang, we're reviewing our PRs. Can you please file the CLA soon, or we may need to close this PR due to inactivity? Thank you.

**Comment by billabt** [comment]
Fixed upstream.  Thanks for contribution anyway.

**Pull request closed without merging**
